Vagrant.configure("2") do |config|
    config.vm.define :lesson_3_vm do |lesson_3_vm|
      lesson_3_vm.vm.box = "centos/7"
      lesson_3_vm.vm.box_version = "1804.02"
    end
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 4
      libvirt.memory = 14000
      libvirt.storage :file, :size => '10G'
      libvirt.storage :file, :size => '2G'
      libvirt.storage :file, :size => '1G'
      libvirt.storage :file, :size => '1G'
    end
  
    $script = <<-SCRIPT
      yum install mdadm lvm2 xfsdump -y
    SCRIPT
  
    config.vm.provision "shell",
      inline: $script
  end
  


